id: AB01CC4B0
title: The Mantra Collection that Incinerates All the Diseases of this Kaliyuga
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 04:38:08.857370
  last_modified_at: 2022-03-01 04:38:08.857378
